version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "4430:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    extra_hosts:
      - host.docker.internal:host-gateway